<!DOCTYPE html>
<html lang="fr" >
<?php include ("head.php"); ?>
<body>

	<?php include ("menu.php"); ?>

	<br/><br/><br/><br/>   


	<center><h3>Conditions générales de vente</h3></center>  

	Article 1 : Objet Les présentes Conditions Générales de Vente déterminent les droits et obligations des parties dans le cadre de la vente en ligne de Produits ou Services proposés par le Vendeur. 
	<br/><br/>
Article 2 : Dispositions générales Les présentes Conditions Générales de Vente (CGV) régissent les ventes de Produits ou de Services, effectuées au travers des sites Internet de l’association, et sont partie intégrante du Contrat entre l’Acheteur et EF’Ride. Elles sont pleinement opposables à l’Acheteur qui les a acceptés avant de passer commande. EF’Ride se réserve la possibilité de modifier les présentes, à tout moment par la publication d’une nouvelle version sur son site Internet. Les CGV applicables alors sont celles étant en vigueur à la date du paiement (ou du premier paiement en cas de paiements multiples) de la commande. Ces CGV sont consultables sur le site Internet de de l’association à l’adresse suivante : www.efride.fr L’association s’assure également que leur acceptation soit claire et sans réserve en mettant en place une case à cocher et un clic de validation. Le Client déclare avoir pris connaissance de l’ensemble des présentes Conditions Générales de Vente, et le cas échéant des Conditions Particulières de Vente liées à un produit ou à un service, et les accepter sans restriction ni réserve. Le Client reconnaît qu’il a bénéficié des conseils et informations nécessaires afin de s’assurer de l’adéquation de l’offre à ses besoins. Le Client déclare être en mesure de contracter légalement en vertu des lois françaises ou valablement représenter la personne physique ou morale pour laquelle il s’engage. Sauf preuve contraire les informations enregistrées par la Société constituent la preuve de l’ensemble des transactions. 
<br/><br/>

Article 3 : Conclusion du contrat en ligne Conformément aux dispositions de l’article 1127-1 du Code civil, le Client doit suivre une série d’étapes pour conclure le contrat par voie électronique pour pouvoir réaliser sa commande : – Information sur les caractéristiques essentielles du Produit ; – Choix du Produit, le cas échéant, de ses options - Indication des coordonnées essentielles du Client (identification, email, adresse…) ; – Acceptation des présentes Conditions Générales de Vente – Vérification des éléments de la commande (formalité du double clic) et, le cas échéant, correction des erreurs. Avant de procéder à sa confirmation, l’Acheteur a la possibilité de vérifier le détail de sa commande, son prix, et de corriger ses éventuelles erreurs, ou annuler sa commande. La confirmation de la commande emportera formation du présent contrat. – Ensuite, suivi des instructions pour le paiement, paiement des produits, puis livraison de la commande. Le Client recevra confirmation par courrier électronique du paiement de la commande, ainsi qu’un accusé de réception de la commande la confirmant. Le client renseigne le formulaire de procédure d’achat lui-même et sans action du vendeur. Si le vendeur remplie, coche, ou effectue une ou plusieurs actions sur le processus de commande, le client peut se retourner contre lui. Et ce du choix du billet jusqu’à la finalisation du paiement. Le client disposera pendant son processus de commande de la possibilité d’identifier d’éventuelles erreurs commises dans la saisie des données et de les corriger. La langue proposée pour la conclusion du contrat est la langue française. L’archivage des communications, de la commande, des détails de la commande, ainsi que des factures est effectué sur un support fiable et durable de manière constituer une copie fidèle et durable conformément aux dispositions de l’article 1360 du code civil. Ces informations peuvent être produites à titre de preuve du contrat. Pour les produits livrés, la livraison se fera à l’EFREI situé au 30 - 32 avenue de la République 94800 Villejuif. Aux fins de bonne réalisation de la commande, le Client s’engage à fournir des éléments d’identification véridiques. Le Vendeur se réserve la possibilité de refuser la commande, par exemple pour toute demande anormale, réalisée de mauvaise foi ou pour tout motif légitime. 
<br/><br/>

Article 4 : Produits et services les caractéristiques essentielles des biens, des services et leurs prix respectifs sont mis à disposition de l’acheteur sur les sites Internet de l’association. Conformément à l’article L112-1 du Code la consommation, le consommateur est informé, par voie de marquage, d’étiquetage, d’affichage ou par tout autre procédé approprié, des prix et des conditions particulières de la vente et de l’exécution des services avant toute conclusion du contrat de vente. Dans tous les cas, le montant total dû par l’Acheteur est indiqué sur la page de confirmation de la commande. Le prix de vente du produit est celui en vigueur indiqué au jour de la commande, celui-ci ne comportant par les frais de ports facturés en supplément. Ces éventuels frais sont indiqués à l’Acheteur lors du process de vente, et en tout état de cause au moment de la confirmation de la commande. Le client atteste avoir reçu un détail des modalités de paiement, et d’exécution du contrat, ses coordonnées postales, téléphoniques et électroniques, et à ses activités dans le contexte de la présente vente. Le Vendeur s’engage à honorer la commande du Client dans la limite des stocks de Produits disponibles uniquement. La personne qui encaisse un paiement en espèce est considéré comme le vendeur et en assume sa responsabilité. A défaut, le vendeur en informe le Client ; si la commande a été passée, le Vendeur rembourse le client. Les informations contractuelles sont présentées en détail et en langue française. Les parties conviennent que les illustrations ou photos des produits offerts à la vente n’ont pas de valeur contractuelle. La durée de validité de l’offre des Produits ainsi que leurs prix est précisée sur les sites Internet de l’association, ainsi que la durée minimale des contrats proposés lorsque ceux-ci portent sur une fourniture continue ou périodique de produits ou services. Sauf conditions particulières, les droits concédés au titre des présentes le sont uniquement à la personne physique signataire de la commande (ou la personne titulaire de l’adresse email communiquée). 
<br/><br/>
Article 5 : Conformité Conformément à l’article L.411-1 du Code de la consommation, les produits et les services offerts à la vente au travers des présentes CGV répondent aux prescriptions en vigueur relatives à la sécurité et à la santé des personnes, à la loyauté des transactions commerciales et à la protection des consommateurs. Indépendamment de toute garantie commerciale, le Vendeur reste tenu des défauts de conformité et des vices cachés du produit. Conformément à l’article L.217-4, le vendeur livre un bien conforme au contrat et répond des défauts de conformité existant lors de la délivrance. Il répond également des défauts de conformité résultant de l’emballage. Conformément aux dispositions légales en matière de conformité et de vices cachés (art. 1641 c. civ.), le Vendeur rembourse ou échange les produits défectueux ou ne correspondant pas à la commande. Le remboursement peut être demandé de la manière suivante : (décrire la procédure de remboursement, et comment le produit doit être retourné. 
<br/><br/>
Article 6 : Le paiement est exigible immédiatement à la commande, y compris pour les produits en précommande. Le Client peut effectuer le règlement par carte de paiement ou espèce. Les cartes émises par des banques domiciliées hors de France doivent obligatoirement être des cartes bancaires internationales (Mastercard ou Visa). Le paiement sécurisé en ligne par carte bancaire est réalisé par notre prestataire de paiement. Les informations transmises sont chiffrées dans les règles de l’art et ne peuvent être lues au cours du transport sur le réseau (décrire le process). Une fois le paiement lancé par le Client, la transaction est immédiatement débitée après vérification des informations. Conformément aux dispositions du Code monétaire et financier, l’engagement de payer donné par carte est irrévocable. En communiquant ses informations bancaires lors de la vente, le Client autorise le Vendeur à débiter sa carte du montant relatif au prix indiqué. Le Client confirme qu’il est bien le titulaire légal de la carte à débiter et qu’il est légalement en droit d’en faire usage. En cas d’erreur, ou d’impossibilité de débiter la carte, la Vente est immédiatement résolue de plein droit et la commande annulée. 
<br/><br/>
Article 7 : Délai de rétractation Conformément aux dispositions de l’article L 221-5 du Code de la consommation, l’Acheteur dispose du droit de se rétracter sans donner de motif, dans un délai de quatorze (14) jours à la date de réception de sa commande. Le droit de rétractation peut être exercé en contactant l’association de la manière suivante : contact@efride.fr, avec ci-joint : numéro d’attestation, contributeur, type de transaction à rembourser et la raison, RIB (si remboursement par virement bancaire), ainsi que le mode de versement. Nous informons les Clients que conformément aux dispositions des articles L. 221-18 à L. 221-28 du Code de la consommation, ce droit de rétractation ne peut être exercé pour (les biens matériels). En cas d’exercice du droit de rétractation dans le délai susmentionné, le prix du ou des produits achetés et les frais de retour restant à la charge du Client. Les retours des produits sont à effectuer dans leur état d’origine et complets (emballage, accessoires, notice…) ; ils doivent si possible être accompagnés d’une copie du justificatif d’achat. 
<br/><br/>
Article 8 : Droits de propriété intellectuelle Les marques, noms de domaines, produits, logiciels, images, vidéos, textes ou plus généralement toute information objet de droits de propriété intellectuelle sont et restent la propriété exclusive du vendeur. Aucune cession de droits de propriété intellectuelle n’est réalisée au travers des présentes CGV. Toute reproduction totale ou partielle, modification ou utilisation de ces biens pour quelque motif que ce soit est strictement interdite. 
<br/><br/>
Article 9 : Force majeure L’exécution des obligations du vendeur au terme des présentes est suspendue en cas de survenance d’un cas fortuit ou de force majeure qui en empêcherait l’exécution. Le vendeur avisera le client de la survenance d’un tel évènement dès que possible. 
<br/><br/>
Article 10 : Nullité et modification du contrat si l’une des stipulations du présent contrat était annulée, cette nullité n’entraînerait pas la nullité des autres stipulations qui demeureront en vigueur entre les parties. Toute modification contractuelle n’est valable qu’après un accord écrit et signé des parties. 
<br/><br/>
Article 11 : Droit applicable et clauses toutes les clauses figurant dans les présentes conditions générales de vente, ainsi que toutes les opérations d’achat et de vente qui y sont visées, seront soumises au droit français. La nullité d’une clause contractuelle n’entraîne pas la nullité des présentes conditions générales de vente. 
<br/><br/>
Article 12 : Vous avez pris conscient du règlement intérieur des infrastruces dans lequel vous pratiquez le sport ou activité. Vous acceptez par la présence de ce formulaire être pris en photo et vidéo, d’être diffuser sur toute les plateformes médiatiques possible. 

<br/><br/><br/>

Mise à jour le 10 avril 2020.
       



	<?php include ("footer.php"); ?>

</body>
</html>
